In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.16.5


create null vector

In [9]:
vector= np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
matrix= np.array([[1,2,4],[4,5,6],[7,8,9]])
# selecting the matrix
matrix[2,1:2]

important functions

In [48]:
# generates random numbers from 0-10
np.random.randint(0,10)

# generates a sequence range from 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# generate random numbers

In [26]:
# seed: generates same random numbers if numbers inside seed is same and used before random.randint 
# reshape: generates the 1 dimensional to any dimensional
np.random.seed(123)
arr= np.random.randint(0,100,20).reshape(5,-1)
arr

array([[66, 92, 98, 17],
       [83, 57, 86, 97],
       [96, 47, 73, 32],
       [46, 96, 25, 83],
       [78, 36, 96, 80]])

In [18]:
# shape: shape of the array
# size: no of elements of the array
arr.shape
arr.size

(4, 5)

In [31]:
arr2.shape
arr2.size

20

horizontal and vertical statickng

In [40]:
np.random.seed(12)
arr1= np.random.randint(1,20,4)

In [41]:
np.random.seed(13)
arr2= np.random.randint(1,20,4)

In [45]:
np.vstack((arr1,arr2))

array([[12,  7, 18,  3],
       [19, 17, 11, 17]])

In [34]:
np.random.seed(123)
matr1= np.random.randint(0,100,20).reshape(5,-1)
matr1

array([[66, 92, 98, 17],
       [83, 57, 86, 97],
       [96, 47, 73, 32],
       [46, 96, 25, 83],
       [78, 36, 96, 80]])

In [ ]:
np.random.seed(124)
matr2=np.random.randint(0,100,20).reshape(5,-1)
matr2

In [ ]:
np.vstack((matr1,matr2))

In [39]:
np.hstack((matr1,matr2))

array([[66, 92, 98, 17, 78, 28, 17,  7],
       [83, 57, 86, 97, 66, 41, 64, 20],
       [96, 47, 73, 32, 28, 78, 21, 21],
       [46, 96, 25, 83, 60, 91, 73, 94],
       [78, 36, 96, 80, 46, 48,  9, 73]])

# numpy vs list

numpy is faster than typical list

In [46]:
%%timeit
list1= [i**2 for i in range(0,10)]

6.17 µs ± 344 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [49]:
%timeit np.arange(0,10)**2

2.21 µs ± 81.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
